import React from "react";


// Talking about the restaurant (reservations, special occasions, events)
const restaurant = ["Le café dispose-t-il d'une terrasse extérieure?",
"Le café peut-il organiser des repas d'affaires?",
"Acceptez-vous les groupes pour des événements privés",
"Emma, quel est le meilleur endroit pour s'asseoir au café",
"Emma, quel est ton plat préféré à servir",
"Est-ce que le café accueille des expositions d'art ou des artistes locaux",
"Est-ce que le café de la Rose a un programme de fidélité",
"Est-ce que le café de la Rose accueille des événements littéraires",
"Est-ce que le café propose des soirées musicales",
"Est-ce que le café vend des produits artisanaux locaux",
"Est-ce que le Wi-Fi est disponible au café",
"Est-ce que le Wi-Fi est disponible pour les clients",
"Est-il possible de privatiser le café pour un événement",
" Est-il possible de réserver une table",
"Le café a-t-il un espace dédié pour lire ou travailler",
"Le café a-t-il une bibliothèque ou des livres à disposition",
"Le café a-t-il une option de privatisation pour les événements",
"Le café a-t-il une option pour un dîner romantique",
"Le café a-t-il une terrasse extérieure",
"Le café de la Rose a-t-il des journaux ou des magazines à lire",
" Le café de la Rose a-t-il des partenariats avec des producteurs locaux",
"Le café de la Rose a-t-il été récompensé ou reconnu",
"Le café de la Rose propose-t-il des événements pour les amateurs de littérature",
"Le café de la Rose vend-il des produits locaux",
"Le café dispose-t-il d'espaces privés pour des réunions",
"Le café dispose-t-il d'un espace pour les réunions d'affaires",
"Le café dispose-t-il d'une connexion Wi-Fi gratuite",
"Le café dispose-t-il d'une salle pour des expositions",
" Le café dispose-t-il d'une terrasse extérieure",
"Le café est-il accessible aux personnes à mobilité réduite",
"Le café est-il adapté aux familles avec enfants",
"Le café est-il adapté pour lire ou étudier",
" Le café est-il ouvert les jours fériés",
"Le café offre-t-il des services traiteur",
"Le café offre-t-il un service de commande pour des occasions spéciales",
"Le café organise-t-il des ateliers culinaires",
"Le café organise-t-il des dégustations de vin",
"Le café organise-t-il des soirées thématiques",
"Le café peut-il accueillir des personnes en fauteuil roulant",
" Le café propose-t-il des cadeaux ou des cartes-cadeaux",
"Le café propose-t-il des conférences ou des rencontres avec des auteurs",
"Le café propose-t-il des livraisons à domicile",
" Le café propose-t-il des options bio",
"Le café propose-t-il des plats à emporter",
" Le café propose-t-il des repas pour les grandes occasions",
"Le café propose-t-il des repas rapides",
" Le café propose-t-il des spécialités de la région de Provence",
" Le café propose-t-il des spécialités locales",
"Le café propose-t-il des spécialités végétariennes",
" Le café propose-t-il un menu pour les enfants",
" Le café utilise-t-il des produits de saison",
"Le café vend-il des produits faits maison à emporter",
"Le café vend-il ses propres produits",
" Le menu change-t-il fréquemment",
" Le menu change-t-il selon les saisons",
"Le menu du café change-t-il fréquemment",
"Le menu inclut-il des plats typiques d'autres régions de France",
"Le menu inclut-il des plats végétaliens",
"Les animaux de compagnie sont-ils autorisés au café",
" Les enfants ont-ils un espace de jeux au café",
"Les enfants ont-ils un menu spécial",
" Les enfants peuvent-ils participer à des ateliers de pâtisserie",
"Les enfants sont-ils bienvenus au café",
" Les produits sont-ils frais et locaux",
" Les produits utilisés sont-ils locaux",
"Les réservations sont-elles nécessaires pour le weekend",
" Les réservations sont-elles recommandées pour le dîner",
" Offrez-vous des services de traiteur pour des événements",
"Organisez-vous des dégustations de vins ou de fromages",
"Organisez-vous des événements culturels au café",
"Organisez-vous des événements pour les enfants",
"Peut-on acheter des produits locaux au café",
" Peut-on organiser des ateliers ou des cours au café",
" Peut-on organiser des repas d'affaires au café",
"Peut-on organiser des événements privés au café",
"Peut-on organiser un brunch de groupe au café",
"Peut-on organiser un dîner romantique au café",
"Peut-on organiser une dégustation de pâtisseries",
"Peut-on réserver le café pour des événements",
" Peut-on réserver le café pour une soirée privée",
"Peut-on réserver une table pour une date spécifique",
"Peut-on venir avec des poussettes ou des landaus",
"Peut-on écouter de la musique française traditionnelle au café",
"Pouvez-vous me parler de l'ambiance du Café de la Rose",
"Pouvons-nous acheter les produits de votre café",
"Pouvons-nous venir avec des enfants en bas âge",
"Proposez-vous des événements culturels en lien avec la gastronomie",
"Puis-je amener mon propre gâteau pour une célébration",
"Puis-je organiser un petit événement au café",
"Puis-je trouver des souvenirs du café à acheter",
" Quels sont vos horaires d'ouverture",
"Votre café est-il engagé dans le développement durable",
"Y a-t-il des soirées poésie ou lectures au café",
" Y a-t-il des événements culturels organisés au café",
"Y a-t-il une option de plats à emporter",
" Y a-t-il une spécialité de Provence que vous recommandez"
];

// Talking about food (dietary restrictions, menu, recommendations)
const food = ["Avez-vous des options sans sucre ajouté",
"Avez-vous des recommandations pour un déjeuner léger",
"Avez-vous des recommandations pour un plat léger",
"Avez-vous des spécialités du jour",
"Disposez-vous d'options pour les régimes hypocaloriques",
"Disposez-vous d'un menu pour enfants",
"Emma, as-tu une pâtisserie française favorite",
"Emma, pouvez-vous préparer un menu surprise",
"Emma, pouvez-vous préparer un plat sans certains ingrédients",
"Emma, quel est le meilleur dessert pour un amateur de chocolat",
"Emma, quel est le plat que vous recommanderiez pour un premier visiteur",
"Emma, quel est votre dessert français préféré",
"Emma, quel est votre plat français préféré",
"Emma, quel est votre plat provençal préféré",
"Emma, quel est votre plat préféré au café",
"Emma, quel est votre pâtisserie préférée dans le café",
" Emma, quelle est votre recommandation pour un dessert",
"Emma, êtes-vous impliquée dans la création des plats du menu",
"Est-ce que Emma peut aider à choisir un plat pour un régime spécifique",
" Est-ce que Emma peut recommander un plat pour un régime spécifique",
"Est-ce que le café a des options pour les intolérants au lactose ",
 "Est-ce que le café a des options pour les régimes spéciaux",
" Est-ce que le café de la Rose a un plat du jour",
"Est-ce que le café organise des ateliers ou des cours de cuisine",
"Est-ce que le café propose des ateliers pour enfants",
"Est-ce que le café propose des repas à thème régional",
"Le café a-t-il des options de plats chauds et froids",
"Le café a-t-il des options pour les cœliaques",
"Le café a-t-il des options pour les personnes allergiques aux noix",
" Le café a-t-il des options pour les régimes spécifiques",
" Le café a-t-il des options végétaliennes pour le petit-déjeuner",
"Le café a-t-il des plats inspirés par d'autres cultures",
" Le café a-t-il des spécialités de saison",
"Le café a-t-il un menu du jour",
"Le café a-t-il un plat du jour",
" Le café a-t-il une option de menu pour les végétariens",
"Le café de la Rose a-t-il des options de petit-déjeuner",
"Le café de la Rose a-t-il des options sans gluten",
"Le café de la Rose a-t-il des plats sans lactose",
"Le café de la Rose a-t-il des recettes traditionnelles françaises",
"Le café de la Rose a-t-il un menu saisonnier",
"Le café de la Rose a-t-il un plat signature",
"Le café de la Rose propose-t-il des formules petit-déjeuner",
"Le café de la Rose propose-t-il des plats pour les enfants",
"Le café de la Rose propose-t-il des plats typiques de Provence",
"Le café de la Rose propose-t-il des viennoiseries",
" Le café de la Rose vend-il ses propres créations culinaires",
"Le café offre-t-il des alternatives de sucre",
" Le café offre-t-il des cours de pâtisserie",
"Le café offre-t-il des options pour les intolérants au gluten",
" Le café offre-t-il des options véganes",
"Le café offre-t-il des plats à partager pour deux personnes",
"Le café offre-t-il une expérience gastronomique provençale authentique",
"Le café propose-t-il des desserts sans gluten",
" Le café propose-t-il des options végétariennes",
"Le café propose-t-il des plats sans produits laitiers",
" Le café propose-t-il des salades de fruits frais",
"Le café propose-t-il des sandwichs ou des paninis",
" Le café propose-t-il des spécialités de boulangerie françaises",
" Le café sert-il des crêpes",
" Le café sert-il des plats biologiques",
" Le café sert-il des quiches variées",
" Le café utilise-t-il des ingrédients frais et locaux",
"Le café utilise-t-il des ingrédients équitables",
"Le menu inclut-il des plats sans lactose",
" Les desserts du café sont-ils faits maison",
"Les produits de pâtisserie sont-ils faits maison",
"Les repas sont-ils préparés sur place",
"Peut-on acheter des pâtisseries françaises à emporter",
" Peut-on acheter les pâtisseries en grande quantité",
"Peut-on apporter son gâteau d'anniversaire au café",
"Peut-on avoir des plats à partager",
"Peut-on emporter des pâtisseries en grande quantité",
"Peut-on trouver des options sans sucre au café",
"Peut-on trouver des produits sans sel au café",
"Pouvons-nous commander des plats pour des occasions spéciales",
" Proposez-vous des formules déjeuner",
" Puis-je avoir la liste des ingrédients d'un plat",
"Puis-je trouver des plats typiques de la Provence au café",
"Quelle est la pâtisserie la plus populaire du café",
"Quelle est la spécialité de la maison",
" Y a-t-il des options de desserts sans sucre",
"Y a-t-il des options de repas légers",
" Y a-t-il des options de repas pour les sportifs",
"Y a-t-il des options halal ou casher au menu",
"Y a-t-il des options pour les personnes ayant des restrictions alimentaires",
"Y a-t-il des options véganes au menu",
"Y a-t-il des options végétariennes au café",
" Y a-t-il des plats pour les amateurs de viande",
"Y a-t-il des plats sans gluten disponibles",
"Y a-t-il des spécialités sucrées pour les personnes diabétiques",
"Y a-t-il des spécialités sucrées pour les végétaliens"
];

// Talking about beverages (types of drinks, dietary restrictions)
const beverages = ["Emma, pouvez-vous recommander un vin français?",
"Avez-vous des spécialités de café froid",
"Avez-vous une sélection de thés",
"Emma, proposez-vous des boissons locales",
"Emma, quel est le meilleur café du menu",
"Emma, quel est le meilleur thé du menu",
"Emma, quel est votre vin préféré du menu",
" Est-ce qu'Emma peut nous recommander un vin",
"Est-ce que le café dispose d'un choix de vins français",
"Est-ce que le café propose des formules pour le thé de l'après-midi",
" Est-ce que le café propose des jus de fruits frais pressés",
"Est-ce que le café vend ses propres mélanges de café ou de thé",
" Le café a-t-il des spécialités de café froid",
"Le café a-t-il une sélection de thés",
"Le café a-t-il une sélection de vins biologiques",
"Le café a-t-il une sélection de vins de la région Provence",
"Le café de la Rose offre-t-il des spécialités de café",
" Le Café de la Rose propose-t-il des boissons alcoolisées",
"Le café de la Rose propose-t-il des thés aromatisés",
"Le café offre-t-il des alternatives au lait traditionnel",
"Le café offre-t-il des options bio pour les boissons",
" Le café propose-t-il des alternatives de café pour ceux qui n'aiment pas le café",
"Le café propose-t-il des boissons artisanales",
" Le café propose-t-il des boissons artisanales locales",
"Le café propose-t-il des boissons sans alcool",
"Le café propose-t-il des boissons spéciales en hiver",
" Le café propose-t-il des boissons végétaliennes",
"Le café propose-t-il des jus de fruits frais",
" Le café propose-t-il des options sans caféine",
"Le café sert-il des boissons énergisantes",
"Le café sert-il des boissons énergétiques ou des smoothies",
"Le café vend-il ses propres mélanges de café",
"Les boissons sont-elles biologiques",
" Les boissons sont-elles préparées à la commande",
"Offrez-vous des boissons spéciales pendant les fêtes",
" Peut-on apporter son vin au café",
" Peut-on commander des boissons alcoolisées",
"Peut-on commander des boissons pour accompagner les pâtisseries",
" Peut-on commander des boissons sans sucre",
"Peut-on commander des boissons spéciales",
" Peut-on commander des boissons à base de plantes",
"Peut-on commander du café à emporter",
"Peut-on déguster des vins locaux au café",
" Pouvons-nous commander des boissons spéciales au café",
"Proposez-vous des alternatives au lait de vache",
"Proposez-vous des boissons sans alcool",
"Y a-t-il des options de café biologique au café",
" Y a-t-il des options de café décaféiné"
];

// Paying (discounts, ways to pay)
const paying = ["Avez-vous des options de paiement sans contact",
"Est-ce que le café de la Rose fait des réductions pour les groupes",
"Faites-vous des réductions pour les étudiants ou les seniors",
"Le café a-t-il des offres pour les anniversaires",
"Le café de la Rose fait-il des réductions pour les anciens clients",
"Peut-on payer en espèces au café",
" Y a-t-il des réductions pour les grandes réservations",
"Y a-t-il des réductions pour les réservations de groupe"]

// Getting to Know Emma :) - probably exclude
const social = ["Emma, pourrais-je avoir une recommandation de livre français",
"Emma, pouvez-vous recommander un bon livre français",
" Emma, pouvez-vous recommander un livre français"];

const Categories = () => {
  return (
    
  );
};

export default Categories;
